# Generated by Django 4.1.1 on 2022-09-24 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperbook',
            name='Illustrations',
            field=models.CharField(blank=True, choices=[('Немає ілюстрацій', 'Немає ілюстрацій'), ('Чорно-білі', 'Чорно-білі'), ('Кольорові', 'Кольорові')], max_length=100, null=True, verbose_name='Ілюстрації'),
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(max_length=300, verbose_name='Зміст рецензії')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.paperbook', verbose_name='Книга')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
    ]
