# Generated by Django 4.1.1 on 2022-09-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_alter_paperbook_illustrations_bookreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Жахливо'), (2, 'Погано'), (3, 'Середньо'), (4, 'Чудово'), (5, 'Ідеально')], null=True),
        ),
    ]
