# Generated by Django 4.1.1 on 2022-09-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_bookreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperbook',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
