# Generated by Django 4.1.1 on 2022-10-03 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstore', '0004_paperbook_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Жахливо'), (2, 'Погано'), (3, 'Середньо'), (4, 'Чудово'), (5, 'Ідеально')], null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='paperbook',
            name='rating',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='LikeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.bookreview', verbose_name='Рецензія')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
    ]
